title: Linlian Jiang
logo: /assets/img/lo.jpg
description: CV & CG, No. 2699 Qianjin Street, Changchun, Jilin email: jiangll21@mail.jlu.edu.cn
show_downloads: false
email: jiangll21@mail.jlu.edu.cn
theme: jekyll-theme-minimal
